name: Assign PR Reviewer

on:
  pull_request:
    types: [opened, ready_for_review]
    branches: [main]  # 监听目标为主干的 PR
permissions:
  contents: write 

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get source branch creator
        id: get-creator
        run: |
          # 提取来源分支名
          SOURCE_BRANCH="${{ github.head_ref }}"

          # 从文件 branches_creators.txt 中查找创建者
          CREATOR=$(grep "^${SOURCE_BRANCH}:" branches_creators.txt | cut -d':' -f2)
          
          if [ -z "$CREATOR" ]; then
            echo "::warning::No creator found for branch $SOURCE_BRANCH"
            exit 0
          fi

          echo "creator=$CREATOR" >> $GITHUB_OUTPUT

      - name: Assign reviewer via GitHub API
        if: steps.get-creator.outputs.creator
        uses: actions/github-script@v6
        with:
          script: |
            const { creator } = process.env;
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [creator]
            });
        env:
          creator: ${{ steps.get-creator.outputs.creator }}
