name: Set Branch Protection

on:
  create:
    branches: ['**']  # 监听所有分支创建事件

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch creator
        env:
          BRANCH: ${{ github.ref_name }}
          CREATOR: ${{ github.actor }}
        run: |
          echo "Branch $BRANCH created by $CREATOR"
          # 调用GitHub API更新分支保护规则
          curl -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/branches/$BRANCH/protection" \
          -d '{
            "required_pull_request_reviews": {
              "require_code_owner_reviews": false,
              "required_approving_review_count": 1,
              "restrict_approvals": true,
              "users": ["'$CREATOR'"]
            },
            "enforce_admins": false,
            "required_status_checks": null,
            "restrictions": null
          }'
