name: Track Branch Creator

on:
  create:
    branches: ['**']

jobs:
  track-creator:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug branch info
        run: |
          echo "Branch name: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"

      - name: Append branch creator to file
        run: |
          # 拉取最新代码避免冲突
          git config --global pull.rebase true
          git pull origin main

          # 追加记录到文件
          echo "$BRANCH:$CREATOR" >> branches_creators.txt

          # 提交变更
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add branches_creators.txt
          git commit -m "Track creator of branch $BRANCH"
          git push
        env:
          BRANCH: ${{ github.ref_name }}
          CREATOR: ${{ github.actor }}
